### PR TITLE
Fix divide by zero

### PR DESCRIPTION
**Pull request by dmfilipenko**
Sometimes I've got an error on MacOS when I'm using a touchpad.

### CODE REVIEW

**Comment by dmfilipenko** [comment]
I've got delta equal to **-0**.  And **-0** not equal **0**

**Comment by andrepolischuk** [comment]
Are you sure? Actually `-0 === 0 === +0`.

Article about [signed zero](http://www.2ality.com/2012/03/signedzero.html).

**Comment by dmfilipenko** [comment]
@andrepolischuk got it. thanks for clarifications:)

**Comment by andrepolischuk** [comment]
Thanks

**Pull request merged**
